title: prad
email: dev@pradr.com
description: Home
about: incoming swe @ meta
show_downloads: false
google_analytics: UA-108144808-1
include: ['_pages']
favicon: true
color-scheme: manual
repository: pradhapanr/prad-site
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
